language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial
sudo: true
# command to install dependencies
install:
  - pip install -U .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
